/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowershop;

import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
/**
 *
 * @author Dell
 */
//Reused for add, update, delete
public class AddBouquetDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddBouquetDialog
     */
    int bouquetId;
    String bouquetName;
    String bouquetDesc;
    int bouquetQuantity;
    float bouquetPrice;
    int bouquetMinq;
    String bouquetStatus;
    
    public AddBouquetDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        comboBox.addItem("On stock");
        comboBox.addItem("Out of stock");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bouquetNameTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        qty = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        addSaveBouquet = new javax.swing.JButton();
        cancelBouquet1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bouquetCodeTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        deleteLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bouquetPriceTF = new javax.swing.JTextField();
        bouquetMinqTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Name:");

        bouquetNameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bouquetNameTF.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        bouquetNameTF.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Quantity:");

        qty.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        qty.setPreferredSize(new java.awt.Dimension(30, 25));

        description.setColumns(20);
        description.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        description.setRows(5);
        jScrollPane1.setViewportView(description);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Description:");

        addSaveBouquet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addSaveBouquet.setVerifyInputWhenFocusTarget(false);
        addSaveBouquet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSaveBouquetActionPerformed(evt);
            }
        });

        cancelBouquet1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cancelBouquet1.setText("Cancel");
        cancelBouquet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBouquet1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Bouquet Code:");

        bouquetCodeTF.setEditable(false);
        bouquetCodeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bouquetCodeTF.setPreferredSize(new java.awt.Dimension(6, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Status:");

        comboBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        deleteLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteLabel.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Price:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Min. Quantity:");

        bouquetPriceTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bouquetPriceTF.setText("0.00");
        bouquetPriceTF.setPreferredSize(new java.awt.Dimension(6, 25));

        bouquetMinqTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bouquetMinqTF.setPreferredSize(new java.awt.Dimension(6, 25));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(qty, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(bouquetPriceTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bouquetMinqTF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(56, 56, 56)))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bouquetNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(bouquetCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(addSaveBouquet, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelBouquet1)
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bouquetCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bouquetNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(bouquetPriceTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(bouquetMinqTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addSaveBouquet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBouquet1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        bouquetNameTF.requestFocus();
        bouquetPriceTF.setHorizontalAlignment(SwingConstants.RIGHT);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelBouquet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBouquet1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelBouquet1ActionPerformed

    private void addSaveBouquetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSaveBouquetActionPerformed

        bouquetId = Integer.parseInt(bouquetCodeTF.getText());
        bouquetName = bouquetNameTF.getText();
        if(bouquetName.length() == 0)
            JOptionPane.showMessageDialog(null, "Bouquet name required.", "Error",JOptionPane.ERROR_MESSAGE);
        bouquetDesc = description.getText();
        bouquetStatus = comboBox.getSelectedItem().toString();
        try
        {
            bouquetQuantity = (int) qty.getValue();
            bouquetPrice = Float.parseFloat(bouquetPriceTF.getText());
            bouquetMinq = Integer.parseInt(bouquetMinqTF.getText());

            if("Add".equals(evt.getActionCommand()))
            {
                AdminForm ext1 = new AdminForm();
                bouquetNameTF.requestFocusInWindow();
                ext1.addSaveBouquetExt(bouquetId, bouquetName, bouquetDesc, bouquetQuantity, bouquetPrice,
                        bouquetMinq, bouquetStatus);
                dispose();
            }
            else if("Update".equals(evt.getActionCommand()))
            {
                AdminForm ext2 = new AdminForm();
                ext2.updateSaveBouquetExt(bouquetId, bouquetName, bouquetDesc, bouquetQuantity, bouquetPrice,
                        bouquetMinq, bouquetStatus);
                dispose();
            }
            else if("Delete".equals(evt.getActionCommand()))
            {
                AdminForm ext3 = new AdminForm();
                ext3.deleteSaveBouquetExt(bouquetId);
                dispose();
            }
        }
        catch(NumberFormatException | SQLException e)
        {
            bouquetQuantity = 0;
            bouquetPrice = 0;
            bouquetMinq = bouquetQuantity;
        }

    }//GEN-LAST:event_addSaveBouquetActionPerformed

    public JButton getAddSaveBouquet()
    {
        return addSaveBouquet;
    }
    
    public JLabel getDeleteLabel()
    {
        return deleteLabel;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBouquetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBouquetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBouquetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBouquetDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddBouquetDialog dialog = new AddBouquetDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSaveBouquet;
    public javax.swing.JTextField bouquetCodeTF;
    public javax.swing.JTextField bouquetMinqTF;
    public javax.swing.JTextField bouquetNameTF;
    public javax.swing.JTextField bouquetPriceTF;
    private javax.swing.JButton cancelBouquet1;
    public javax.swing.JComboBox<String> comboBox;
    private javax.swing.JLabel deleteLabel;
    public javax.swing.JTextArea description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JSpinner qty;
    // End of variables declaration//GEN-END:variables

}