/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package flowershop;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class EmployeeDialog extends javax.swing.JDialog {

    /**
     * Creates new form EmployeeDialog
     */
    int employee_id;
    String employee_last;
    String employee_first;
    String employee_sex;
    String employee_contact;
    String employee_bdate;
    
    public EmployeeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        employeeCodeTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        employeeLNTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        employeeFNTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        contactNoTF = new javax.swing.JTextField();
        employeeApproveButton = new javax.swing.JButton();
        employeeCancelButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        bDateChooser = new com.toedter.calendar.JDateChooser();
        empDeleteLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Employee Code:");

        employeeCodeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Last Name:");

        employeeLNTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        employeeLNTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeLNTFActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("First Name:");

        employeeFNTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Sex:");

        maleRadioButton.setText("Male");

        femaleRadioButton.setText("Female");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Contact No:");

        contactNoTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        employeeApproveButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        employeeApproveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeApproveButtonActionPerformed(evt);
            }
        });

        employeeCancelButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        employeeCancelButton.setText("Cancel");
        employeeCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeCancelButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Birth Date:");

        empDeleteLabel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        empDeleteLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(employeeCodeTF)
                            .addComponent(employeeLNTF)
                            .addComponent(employeeFNTF)
                            .addComponent(contactNoTF, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(femaleRadioButton))
                            .addComponent(bDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(employeeApproveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(employeeCancelButton)
                        .addGap(33, 33, 33)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(empDeleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(empDeleteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(employeeCodeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(employeeLNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(employeeFNTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(bDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maleRadioButton)
                    .addComponent(femaleRadioButton)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(contactNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeApproveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeCancelButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        employeeCodeTF.setEditable(false);
        bDateChooser.setDateFormatString("MM/dd/yyyy");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void employeeLNTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLNTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeLNTFActionPerformed

    private void employeeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeCancelButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_employeeCancelButtonActionPerformed

    private void employeeApproveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeApproveButtonActionPerformed
        // TODO add your handling code here:
        employee_id = Integer.parseInt(employeeCodeTF.getText());
        employee_last = employeeLNTF.getText();
        employee_first = employeeFNTF.getText();
        if((employee_last.isEmpty() || employee_first.isEmpty()) || (employee_first.isEmpty() && employee_first.isEmpty()))
        {
            JOptionPane.showMessageDialog(null, "Employee names required.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        if(maleRadioButton.isSelected())
        {
            employee_sex = "M";
        }
        if(femaleRadioButton.isSelected())
        {
            employee_sex = "F";
        }
        
        SimpleDateFormat bdateFormat = new SimpleDateFormat("yyyy-MM-dd");
        employee_bdate = bdateFormat.format(bDateChooser.getDate());
        try
        {
            employee_contact = contactNoTF.getText();
            
            if("Add".equals(evt.getActionCommand()))
            {
                AdminForm add_emp = new AdminForm();
                add_emp.addEmployeeExt(employee_id, employee_last, employee_first, employee_sex, employee_bdate, employee_contact);
                dispose();
            }
            else if("Update".equals(evt.getActionCommand()))
            {
                AdminForm update_emp = new AdminForm();
                update_emp.updateEmployeeExt(employee_id, employee_last, employee_first, employee_sex, employee_bdate, employee_contact);
                dispose();
            }
            else if("Delete".equals(evt.getActionCommand()))
            {
                AdminForm delete_emp = new AdminForm();
                delete_emp.deleteEmployeeExt(employee_id);
                dispose();
            }
        }
        catch(SQLException e)
        {
            employee_contact = "None";
        }
    }//GEN-LAST:event_employeeApproveButtonActionPerformed

    public JButton getEmployeeApproveButton()
    {
        return employeeApproveButton;
    }
    
    public JLabel getEmpDeleteLabel()
    {
        return empDeleteLabel;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            EmployeeDialog dialog = new EmployeeDialog(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser bDateChooser;
    public javax.swing.JTextField contactNoTF;
    private javax.swing.JLabel empDeleteLabel;
    private javax.swing.JButton employeeApproveButton;
    private javax.swing.JButton employeeCancelButton;
    public javax.swing.JTextField employeeCodeTF;
    public javax.swing.JTextField employeeFNTF;
    public javax.swing.JTextField employeeLNTF;
    public javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JRadioButton maleRadioButton;
    // End of variables declaration//GEN-END:variables
}
